In [31]:
import numpy as np
from tqdm import tqdm

import models
import preprocessing
import score_utils


In [3]:
scores = preprocessing.get_score_tensors()

Loading score tensors from disk


  0%|          | 0/5930 [00:00<?, ?it/s]

  1%|          | 48/5930 [00:00<00:12, 478.94it/s]

  2%|▏         | 109/5930 [00:00<00:10, 537.45it/s]

  3%|▎         | 155/5930 [00:00<00:11, 507.32it/s]

  4%|▎         | 218/5930 [00:00<00:10, 537.06it/s]

  5%|▍         | 284/5930 [00:00<00:10, 560.59it/s]

  6%|▌         | 339/5930 [00:00<00:10, 558.55it/s]

  7%|▋         | 415/5930 [00:00<00:09, 586.95it/s]

  8%|▊         | 485/5930 [00:00<00:09, 600.52it/s]

  9%|▉         | 561/5930 [00:00<00:08, 616.58it/s]

 11%|█         | 637/5930 [00:01<00:08, 630.32it/s]

 12%|█▏        | 716/5930 [00:01<00:08, 644.55it/s]

 13%|█▎        | 788/5930 [00:01<00:07, 648.99it/s]

 14%|█▍        | 859/5930 [00:01<00:07, 652.93it/s]

 16%|█▌        | 940/5930 [00:01<00:07, 663.80it/s]

 17%|█▋        | 1021/5930 [00:01<00:07, 672.95it/s]

 19%|█▊        | 1103/5930 [00:01<00:07, 681.75it/s]

 20%|█▉        | 1181/5930 [00:01<00:06, 685.89it/s]

 21%|██        | 1258/5930 [00:01<00:06, 687.74it/s]

 22%|██▏       | 1334/5930 [00:01<00:06, 688.76it/s]

 24%|██▎       | 1408/5930 [00:02<00:06, 685.66it/s]

 25%|██▍       | 1479/5930 [00:02<00:06, 682.00it/s]

 26%|██▌       | 1552/5930 [00:02<00:06, 683.96it/s]

 27%|██▋       | 1622/5930 [00:02<00:06, 674.87it/s]

 28%|██▊       | 1687/5930 [00:02<00:06, 668.43it/s]

 29%|██▉       | 1749/5930 [00:02<00:06, 664.21it/s]

 31%|███       | 1829/5930 [00:02<00:06, 669.04it/s]

 32%|███▏      | 1900/5930 [00:02<00:06, 670.20it/s]

 33%|███▎      | 1968/5930 [00:02<00:05, 661.41it/s]

 34%|███▍      | 2036/5930 [00:03<00:05, 662.00it/s]

 36%|███▌      | 2119/5930 [00:03<00:05, 667.28it/s]

 37%|███▋      | 2191/5930 [00:03<00:05, 668.71it/s]

 38%|███▊      | 2261/5930 [00:03<00:05, 628.75it/s]

 39%|███▉      | 2317/5930 [00:03<00:05, 617.53it/s]

 40%|████      | 2372/5930 [00:03<00:05, 615.70it/s]

 41%|████      | 2424/5930 [00:03<00:05, 609.64it/s]

 42%|████▏     | 2476/5930 [00:04<00:05, 607.35it/s]

 43%|████▎     | 2541/5930 [00:04<00:05, 608.26it/s]

 44%|████▍     | 2595/5930 [00:04<00:05, 606.53it/s]

 45%|████▍     | 2649/5930 [00:04<00:05, 602.32it/s]

 46%|████▌     | 2735/5930 [00:04<00:05, 607.96it/s]

 47%|████▋     | 2797/5930 [00:04<00:05, 607.38it/s]

 48%|████▊     | 2861/5930 [00:04<00:05, 607.92it/s]

 49%|████▉     | 2923/5930 [00:04<00:04, 605.88it/s]

 50%|█████     | 2982/5930 [00:04<00:04, 603.32it/s]

 51%|█████     | 3039/5930 [00:05<00:04, 601.30it/s]

 52%|█████▏    | 3102/5930 [00:05<00:04, 601.75it/s]

 54%|█████▎    | 3175/5930 [00:05<00:04, 604.04it/s]

 55%|█████▍    | 3237/5930 [00:05<00:04, 603.33it/s]

 56%|█████▌    | 3298/5930 [00:05<00:04, 603.03it/s]

 57%|█████▋    | 3368/5930 [00:05<00:04, 604.74it/s]

 58%|█████▊    | 3446/5930 [00:05<00:04, 607.77it/s]

 59%|█████▉    | 3518/5930 [00:05<00:03, 609.65it/s]

 60%|██████    | 3587/5930 [00:05<00:03, 609.41it/s]

 62%|██████▏   | 3653/5930 [00:06<00:03, 600.60it/s]

 63%|██████▎   | 3710/5930 [00:06<00:03, 584.57it/s]

 63%|██████▎   | 3756/5930 [00:06<00:03, 581.27it/s]

 64%|██████▍   | 3818/5930 [00:06<00:03, 581.83it/s]

 65%|██████▌   | 3879/5930 [00:06<00:03, 582.17it/s]

 67%|██████▋   | 3945/5930 [00:06<00:03, 583.22it/s]

 68%|██████▊   | 4011/5930 [00:06<00:03, 584.25it/s]

 69%|██████▉   | 4082/5930 [00:06<00:03, 585.95it/s]

 70%|███████   | 4161/5930 [00:07<00:03, 588.83it/s]

 71%|███████▏  | 4229/5930 [00:07<00:02, 588.49it/s]

 72%|███████▏  | 4294/5930 [00:07<00:02, 583.29it/s]

 73%|███████▎  | 4351/5930 [00:07<00:02, 581.87it/s]

 75%|███████▍  | 4424/5930 [00:07<00:02, 583.78it/s]

 76%|███████▌  | 4501/5930 [00:07<00:02, 586.12it/s]

 77%|███████▋  | 4578/5930 [00:07<00:02, 588.46it/s]

 78%|███████▊  | 4647/5930 [00:07<00:02, 589.06it/s]

 79%|███████▉  | 4714/5930 [00:07<00:02, 589.75it/s]

 81%|████████  | 4780/5930 [00:08<00:01, 588.61it/s]

 82%|████████▏ | 4842/5930 [00:08<00:01, 587.23it/s]

 83%|████████▎ | 4901/5930 [00:08<00:01, 581.59it/s]

 84%|████████▍ | 4974/5930 [00:08<00:01, 583.33it/s]

 85%|████████▌ | 5053/5930 [00:08<00:01, 585.71it/s]

 86%|████████▋ | 5125/5930 [00:08<00:01, 587.21it/s]

 88%|████████▊ | 5193/5930 [00:08<00:01, 588.20it/s]

 89%|████████▊ | 5260/5930 [00:08<00:01, 588.62it/s]

 90%|█████████ | 5337/5930 [00:09<00:01, 590.61it/s]

 91%|█████████ | 5411/5930 [00:09<00:00, 592.21it/s]

 92%|█████████▏| 5482/5930 [00:09<00:00, 592.36it/s]

 94%|█████████▎| 5550/5930 [00:09<00:00, 591.25it/s]

 95%|█████████▍| 5624/5930 [00:09<00:00, 592.79it/s]

 96%|█████████▌| 5690/5930 [00:09<00:00, 591.71it/s]

 97%|█████████▋| 5752/5930 [00:09<00:00, 591.24it/s]

 98%|█████████▊| 5812/5930 [00:09<00:00, 590.26it/s]

 99%|█████████▉| 5879/5930 [00:09<00:00, 591.03it/s]

100%|██████████| 5930/5930 [00:10<00:00, 589.94it/s]

In [5]:
metas = preprocessing.get_metadata_tensors()

In [7]:
metas[0].shape

(5, 720, 18)

In [50]:
max_pitch = np.max([np.max(t) for t in scores])
min_pitch = np.min([np.min(t[t > 0]) for t in scores])

In [51]:
min_pitch

31.0

In [12]:
preprocessing.make_input_sequence(scores[0], metas[0], 0, max_pitch).shape

(720, 4, 32, 5, 3)

In [12]:
model = models.conv2dlstm_model()
model.load_weights('./weights/conv2dlstm.weights.best.hdf5')
model.summary()

____________________________________________________________________________________________________
Layer (type)                     Output Shape          Param #     Connected to                     
conv_lst_m2d_1_input (InputLayer (None, None, 32, None 0                                            
____________________________________________________________________________________________________
conv_lst_m2d_1 (ConvLSTM2D)      (None, None, 32, None 40448       conv_lst_m2d_1_input[0][0]       
____________________________________________________________________________________________________
max_pooling3d_1 (MaxPooling3D)   (None, None, 16, None 0           conv_lst_m2d_1[0][0]             
____________________________________________________________________________________________________
conv_lst_m2d_2 (ConvLSTM2D)      (None, 16, None, 64)  221440      max_pooling3d_1[0][0]            
___________________________________________________________________________________________

In [180]:
score_length = 4 * 16  # let's start with 4 bars
score_length

64

In [181]:
# The model is conditioned on a fixed beat pattern
beats = np.zeros((score_length, 16))
for i in range(score_length):
    beats[i, i % 16] = 1
beats

array([[ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  1.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  1., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  1.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  1.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.]])

In [182]:
# Let's first try a score with 5 voices
n_voices = 5
sequence_steps = 4
window_size = 32
gibbs_steps = 100


In [386]:
def sample_softmax(preds, temperature=1.0):
    # taken from https://github.com/keras-team/keras/blob/master/examples/lstm_text_generation.py
    # helper function to sample an index from a probability array
    preds = preds.astype('float64')
    preds = np.log(preds) / temperature
    exp_preds = np.exp(preds)
    preds = exp_preds / np.sum(exp_preds)
    probas = np.random.multinomial(1, preds, 1)
    return np.argmax(probas)

In [642]:
def sample_softmax_multi(preds, temperature=1.0):
    # taken from https://github.com/keras-team/keras/blob/master/examples/lstm_text_generation.py
    # helper function to sample an index from a probability array
    preds = preds.astype('float64')
    preds = np.log(preds) / temperature
    exp_preds = np.exp(preds)
    preds = exp_preds / np.sum(exp_preds, axis=1).reshape((-1, 1))
    probas = np.apply_along_axis(lambda pred: np.random.multinomial(1, pred, 1), 1, preds)
    return probas.argmax(axis=1)

In [643]:
score = np.zeros((n_voices, score_length))
meta = np.zeros((n_voices, score_length, 18))
for i in range(n_voices):
    meta[i, :, 2:] = beats

In [644]:
def sample_1(n_voices, score_length, gibbs_steps, temperature):
    score = np.zeros((n_voices, score_length))
    meta = np.zeros((n_voices, score_length, 18))
    beats = np.zeros((score_length, 16))
    for i in range(score_length):
        beats[i, i % 16] = 1
    for i in range(n_voices):
        meta[i, :, 2:] = beats
    for step in tqdm(range(gibbs_steps)):
        for time_step in range(score_length):
            for voice in range(n_voices):
                input_ = preprocessing.make_input_sequence(score, meta, voice, max_pitch)
                note, slur = model.predict([
                    input_[time_step:time_step+1], beats[time_step:time_step+1]])
                sampled_note = sample_softmax(note[0], temperature)
                slur_proba = np.squeeze(np.array([1 - slur[0], slur[0]]))
                sampled_slur = sample_softmax(slur_proba, temperature)
                if sampled_note > 0:
                    score[voice, time_step] = sampled_note + min_pitch
                else:
                    meta[voice, time_step, score_utils.idx_rest] = 1
                meta[voice, time_step, score_utils.idx_slur] = sampled_slur
    return score, meta

In [645]:
def sample_2(n_voices, score_length, gibbs_steps, temperature):
    score = np.zeros((n_voices, score_length))
    meta = np.zeros((n_voices, score_length, 18))
    beats = np.zeros((score_length, 16))
    for i in range(score_length):
        beats[i, i % 16] = 1
    for i in range(n_voices):
        meta[i, :, 2:] = beats
    for step in tqdm(range(gibbs_steps)):
        for voice in range(n_voices):
            input_ = preprocessing.make_input_sequence(score, meta, voice, max_pitch)
            note, slur = model.predict([
                input_, beats])
            sampled_notes = sample_softmax_multi(note, temperature)
            slur_proba = np.hstack([1 - slur, slur])
            sampled_slurs = sample_softmax_multi(slur_proba, temperature)
            
            score[voice] = sampled_notes + ((sampled_notes > 1) * min_pitch)
            meta[voice, :, score_utils.idx_rest] = sampled_notes == 0
            meta[voice, :, score_utils.idx_slur] = sampled_slurs
    return score, meta

In [651]:
score, meta = sample_2(5, 32, 25, 1)

  0%|          | 0/25 [00:00<?, ?it/s]

  4%|▍         | 1/25 [00:01<00:42,  1.79s/it]

/Users/ben.cohen/miniconda3/envs/palestrinet/lib/python3.6/site-packages/ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in log
  """


  8%|▊         | 2/25 [00:03<00:38,  1.67s/it]

 12%|█▏        | 3/25 [00:04<00:35,  1.61s/it]

 16%|█▌        | 4/25 [00:06<00:32,  1.53s/it]

 20%|██        | 5/25 [00:07<00:29,  1.46s/it]

 24%|██▍       | 6/25 [00:08<00:26,  1.42s/it]

 28%|██▊       | 7/25 [00:09<00:25,  1.39s/it]

 32%|███▏      | 8/25 [00:10<00:23,  1.36s/it]

 36%|███▌      | 9/25 [00:12<00:21,  1.34s/it]

 40%|████      | 10/25 [00:13<00:19,  1.32s/it]

 44%|████▍     | 11/25 [00:14<00:18,  1.31s/it]

 48%|████▊     | 12/25 [00:15<00:16,  1.29s/it]

 52%|█████▏    | 13/25 [00:16<00:15,  1.28s/it]

 56%|█████▌    | 14/25 [00:17<00:14,  1.27s/it]

 60%|██████    | 15/25 [00:18<00:12,  1.27s/it]

 64%|██████▍   | 16/25 [00:20<00:11,  1.26s/it]

 68%|██████▊   | 17/25 [00:21<00:10,  1.26s/it]

 72%|███████▏  | 18/25 [00:22<00:08,  1.25s/it]

 76%|███████▌  | 19/25 [00:23<00:07,  1.25s/it]

 80%|████████  | 20/25 [00:24<00:06,  1.25s/it]

 84%|████████▍ | 21/25 [00:26<00:04,  1.25s/it]

 88%|████████▊ | 22/25 [00:27<00:03,  1.24s/it]

 92%|█████████▏| 23/25 [00:28<00:02,  1.24s/it]

 96%|█████████▌| 24/25 [00:29<00:01,  1.24s/it]

100%|██████████| 25/25 [00:31<00:00,  1.24s/it]

array([[  0.,   0.,   0.,   0.,  49.,   0.,  49.,   0.,   0.,  49.,  56.,
         70.,   0.,   0.,   0.,   0.,   0.,  49.,  63.,  64.,  63.,  70.,
          0.,   0.,  51.,  50.,  49.,  51.,  47.,  49.,  52.,  51.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,  44.,  61.,   0.,   0.,
          0.,   0.,  47.,  58.,  69.,  68.,  71.,  68.,  58.,  68.,  63.,
          0.,   0.,  45.,  46.,   0.,  44.,  56.,  47.,  57.,  51.],
       [  0.,   0.,  54.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  44.,
          0.,   0.,   0.,  42.,  52.,  63.,  59.,   0.,   0.,   0.,   0.,
          0.,  44.,  45.,  44.,  44.,  47.,  44.,  47.,  44.,  54.],
       [  0.,   0.,   0.,   0.,   0.,  49.,  63.,   0.,  51.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,  54.,   0.,   0.,   0.,
          0.,  44.,  47.,  47.,  49.,  37.,   0.,  42.,  44.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,  51.,  54.,  46.,  45.,
         45.,   0.,   0.,  45.,   0.,   0.,   0.,   0.,   

In [654]:
music = score_utils.tensor_to_score(score, meta)

In [655]:
music.write('midi')

'/var/folders/tz/1572h57x6blgvbx33p6nyg3xbw4mw_/T/music21/tmp1r8nx5y_.mid'

In [119]:
score.shape

(5, 256)

In [122]:
meta[2, :, 0]

array([ 0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  0.,
        1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  1.,
        1.,  1.,  1.,  0.,  1.,  0.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,
        1.,  1.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0